import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.

config :noizu_intellect, Noizu.IntellectWeb.Endpoint,
       # Binding to loopback ipv4 address prevents access from other machines.
       # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
       http: [ip: {0, 0, 0, 0}, port: 4123],
       cache_static_manifest: "priv/static/cache_manifest.json",
       server: true,
       root: ".",
       secret_key_base: "fixkSXoEaEai5B7uDDTyGfXsl/TbQ8PUOH1wEBsJQcTfPIE20apPUwvjOGDJQ8C0"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Noizu.Intellect.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
