/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 15-Jul-2023 8:40:36 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS public.account CASCADE
;

DROP TABLE IF EXISTS public.account_agent CASCADE
;

DROP TABLE IF EXISTS public.account_agent_function CASCADE
;

DROP TABLE IF EXISTS public.account_agent_service CASCADE
;

DROP TABLE IF EXISTS public.account_member CASCADE
;

DROP TABLE IF EXISTS public.account_member_role CASCADE
;

DROP TABLE IF EXISTS public.agent_message CASCADE
;

DROP TABLE IF EXISTS public.agent_message_digest CASCADE
;

DROP TABLE IF EXISTS public.channel CASCADE
;

DROP TABLE IF EXISTS public.feature CASCADE
;

DROP TABLE IF EXISTS public.features CASCADE
;

DROP TABLE IF EXISTS public.function CASCADE
;

DROP TABLE IF EXISTS public.intuition_pump CASCADE
;

DROP TABLE IF EXISTS public.message CASCADE
;

DROP TABLE IF EXISTS public.message_features CASCADE
;

DROP TABLE IF EXISTS public.message_functions CASCADE
;

DROP TABLE IF EXISTS public.message_nesting CASCADE
;

DROP TABLE IF EXISTS public.message_services CASCADE
;

DROP TABLE IF EXISTS public.message_subject CASCADE
;

DROP TABLE IF EXISTS public.message_subject_tag CASCADE
;

DROP TABLE IF EXISTS public.prompt_lingua CASCADE
;

DROP TABLE IF EXISTS public.service CASCADE
;

DROP TABLE IF EXISTS public.subject_vector CASCADE
;

DROP TABLE IF EXISTS public.tag_vector CASCADE
;

DROP TABLE IF EXISTS public."user" CASCADE
;

DROP TABLE IF EXISTS public.user_credential CASCADE
;

DROP TABLE IF EXISTS public.user_credential_oauth CASCADE
;

DROP TABLE IF EXISTS public.user_credential_login_pass CASCADE
;

DROP TABLE IF EXISTS public.versioned_string CASCADE
;

DROP TABLE IF EXISTS public.versioned_string_history CASCADE
;

/* Create Tables */

CREATE TABLE public.account
(
	identifier bigint NOT NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.account_agent
(
	identifier bigint NOT NULL,
	account bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.account_agent_function
(
	identifier bigint NOT NULL,
	account_agent bigint NULL,
	function bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.account_agent_service
(
	identifier bigint NOT NULL,
	account_agent bigint NULL,
	service bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.account_member
(
	identifier bigint NOT NULL,
	account bigint NULL,
	"user" bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.account_member_role
(
	identifier bigint NOT NULL,
	account_member bigint NULL,
	account_role bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.agent_message
(
	identifier bigint NOT NULL,
	account_agent bigint NULL,
	content text NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.agent_message_digest
(
	identifier bigint NOT NULL,
	agent_message bigint NULL,
	message bigint NULL
)
;

CREATE TABLE public.channel
(
	identifier bigint NOT NULL,
	account bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.feature
(
	identifier bigint NOT NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.features
(
	identifier bigint NULL,
	message bigint NULL,
	feature varchar(50) NULL
)
;

CREATE TABLE public.function
(
	identifier bigint NOT NULL,
	prompt_file varchar(50) NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.intuition_pump
(
	identifier bigint NOT NULL,
	prompt_file varchar(50) NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.message
(
	identifier bigint NOT NULL,
	sender bigint NULL,
	channel bigint NULL,
	depth smallint NULL,
	contents text NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.message_features
(
	identifier bigint NOT NULL,
	message bigint NULL,
	feature bigint NULL
)
;

CREATE TABLE public.message_functions
(
	identifier bigint NOT NULL,
	message bigint NULL,
	function bigint NULL
)
;

CREATE TABLE public.message_nesting
(
	message bigint NULL,
	depth bigint NULL,
	ancestor bigint NULL
)
;

CREATE TABLE public.message_services
(
	identifier bigint NOT NULL,
	message bigint NULL,
	service bigint NULL
)
;

CREATE TABLE public.message_subject
(
	identifier bigint NOT NULL,
	message bigint NULL,
	subject_vector bigint NULL,
	account_agent bigint NULL
)
;

CREATE TABLE public.message_subject_tag
(
	messsage_subject bigint NOT NULL,
	tag_vector bigint NOT NULL
)
;

CREATE TABLE public.prompt_lingua
(
	identifier bigint NOT NULL,
	prompt_file varchar(50) NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.service
(
	identifier bigint NOT NULL,
	prompt_file varchar(50) NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.subject_vector
(
	identifier bigint NOT NULL
)
;

CREATE TABLE public.tag_vector
(
	identifier bigint NOT NULL
)
;

CREATE TABLE public."user"
(
	identifier bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.user_credential
(
	identifier bigint NOT NULL,
	"user" bigint NULL,
	details bigint NOT NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.user_credential_oauth
(
	identifier bigint NOT NULL,
	provider varchar(50) NULL,
	account varchar(50) NULL
)
;

CREATE TABLE public.user_credential_login_pass
(
	identifier bigint NOT NULL,
	account varchar(50) NULL,
	password varchar(50) NULL
)
;

CREATE TABLE public.versioned_string
(
	identifier bigint NOT NULL,
	version bigint NULL,
	title varchar(50) NULL,
	body varchar(50) NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

CREATE TABLE public.versioned_string_history
(
	identifier bigint NOT NULL,
	versioned_string bigint NULL,
	version bigint NULL,
	title varchar(50) NULL,
	body varchar(50) NULL,
	created_on timestamp without time zone NOT NULL,
	modified_on timestamp without time zone NOT NULL,
	deleted_on timestamp without time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE public.account ADD CONSTRAINT "PK_account"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.account_agent ADD CONSTRAINT "PK_account_agent"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_account_agent_account" ON public.account_agent (account ASC)
;

ALTER TABLE public.account_agent_function ADD CONSTRAINT "PK_account_agent_function"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_account_agent_function_account_agent" ON public.account_agent_function (account_agent ASC)
;

CREATE INDEX "IXFK_account_agent_function_function" ON public.account_agent_function (function ASC)
;

ALTER TABLE public.account_agent_service ADD CONSTRAINT "PK_account_agent_service"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_account_agent_service_account_agent" ON public.account_agent_service (account_agent ASC)
;

CREATE INDEX "IXFK_account_agent_service_service" ON public.account_agent_service (service ASC)
;

ALTER TABLE public.account_member ADD CONSTRAINT "PK_account_member"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_account_member_user" ON public.account_member ("user" ASC)
;

CREATE INDEX "IXFK_account_member_account" ON public.account_member (account ASC)
;

ALTER TABLE public.account_member_role ADD CONSTRAINT "PK_account_member_role"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_account_member_role_account_member" ON public.account_member_role (account_member ASC)
;

ALTER TABLE public.agent_message ADD CONSTRAINT "PK_agent_message"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_agent_message_account_agent" ON public.agent_message (account_agent ASC)
;

ALTER TABLE public.agent_message_digest ADD CONSTRAINT "PK_agent_message_digest"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_agent_message_digest_agent_message" ON public.agent_message_digest (agent_message ASC)
;

CREATE INDEX "IXFK_agent_message_digest_message" ON public.agent_message_digest (message ASC)
;

ALTER TABLE public.channel ADD CONSTRAINT "PK_channel"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_channel_account" ON public.channel (account ASC)
;

ALTER TABLE public.feature ADD CONSTRAINT "PK_feature"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.function ADD CONSTRAINT "PK_function"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.intuition_pump ADD CONSTRAINT "PK_intuition_pump"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.message ADD CONSTRAINT "PK_message"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_message_channel" ON public.message (channel ASC)
;

ALTER TABLE public.message_features ADD CONSTRAINT "PK_message_features"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_message_features_message" ON public.message_features (message ASC)
;

CREATE INDEX "IXFK_message_features_feature" ON public.message_features (feature ASC)
;

ALTER TABLE public.message_functions ADD CONSTRAINT "PK_message_functions"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_message_functions_function" ON public.message_functions (function ASC)
;

CREATE INDEX "IXFK_message_functions_message" ON public.message_functions (message ASC)
;

CREATE INDEX "IXFK_message_nesting_message" ON public.message_nesting (ancestor ASC)
;

CREATE INDEX "IXFK_message_nesting_message_02" ON public.message_nesting (message ASC)
;

ALTER TABLE public.message_services ADD CONSTRAINT "PK_message_services"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_message_services_service" ON public.message_services (service ASC)
;

CREATE INDEX "IXFK_message_services_message" ON public.message_services (message ASC)
;

ALTER TABLE public.message_subject ADD CONSTRAINT "PK_message_subject"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_message_subject_subject_vector" ON public.message_subject (subject_vector ASC)
;

CREATE INDEX "IXFK_message_subject_message" ON public.message_subject (message ASC)
;

CREATE INDEX "IXFK_message_subject_account_agent" ON public.message_subject (account_agent ASC)
;

ALTER TABLE public.message_subject_tag ADD CONSTRAINT "PK_message_subject_tag"
	PRIMARY KEY (messsage_subject,tag_vector)
;

CREATE INDEX "IXFK_message_subject_tag_tag_vector" ON public.message_subject_tag (tag_vector ASC)
;

CREATE INDEX "IXFK_message_subject_tag_message_subject" ON public.message_subject_tag (messsage_subject ASC)
;

ALTER TABLE public.prompt_lingua ADD CONSTRAINT "PK_prompt_lingua"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.service ADD CONSTRAINT "PK_service"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.subject_vector ADD CONSTRAINT "PK_subject_vector"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.tag_vector ADD CONSTRAINT "PK_tag_vector"
	PRIMARY KEY (identifier)
;

ALTER TABLE public."user" ADD CONSTRAINT "PK_user"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.user_credential ADD CONSTRAINT "PK_user_credential"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_user_credential_user" ON public.user_credential ("user" ASC)
;

ALTER TABLE public.user_credential_oauth ADD CONSTRAINT "PK_user_credential_oauth"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_user_credential_oauth_user_credential" ON public.user_credential_oauth (identifier ASC)
;

ALTER TABLE public.user_credential_login_pass ADD CONSTRAINT "PK_user_credential_login_pass"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_user_credential_login_pass_user_credential" ON public.user_credential_login_pass (identifier ASC)
;

ALTER TABLE public.versioned_string ADD CONSTRAINT "PK_versioned_string"
	PRIMARY KEY (identifier)
;

ALTER TABLE public.versioned_string_history ADD CONSTRAINT "PK_versioned_string_history"
	PRIMARY KEY (identifier)
;

CREATE INDEX "IXFK_versioned_string_history_versioned_string" ON public.versioned_string_history (versioned_string ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE public.account_agent ADD CONSTRAINT "FK_account_agent_account"
	FOREIGN KEY (account) REFERENCES public.account (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_agent_function ADD CONSTRAINT "FK_account_agent_function_account_agent"
	FOREIGN KEY (account_agent) REFERENCES public.account_agent (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_agent_function ADD CONSTRAINT "FK_account_agent_function_function"
	FOREIGN KEY (function) REFERENCES public.function (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_agent_service ADD CONSTRAINT "FK_account_agent_service_account_agent"
	FOREIGN KEY (account_agent) REFERENCES public.account_agent (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_agent_service ADD CONSTRAINT "FK_account_agent_service_service"
	FOREIGN KEY (service) REFERENCES public.service (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_member ADD CONSTRAINT "FK_account_member_account"
	FOREIGN KEY (account) REFERENCES public.account (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_member ADD CONSTRAINT "FK_account_member_user"
	FOREIGN KEY ("user") REFERENCES public."user" (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.account_member_role ADD CONSTRAINT "FK_account_member_role_account_member"
	FOREIGN KEY (account_member) REFERENCES public.account_member (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.agent_message ADD CONSTRAINT "FK_agent_message_account_agent"
	FOREIGN KEY (account_agent) REFERENCES public.account_agent (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.agent_message_digest ADD CONSTRAINT "FK_agent_message_digest_agent_message"
	FOREIGN KEY (agent_message) REFERENCES public.agent_message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.agent_message_digest ADD CONSTRAINT "FK_agent_message_digest_message"
	FOREIGN KEY (message) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.channel ADD CONSTRAINT "FK_channel_account"
	FOREIGN KEY (account) REFERENCES public.account (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message ADD CONSTRAINT "FK_message_channel"
	FOREIGN KEY (channel) REFERENCES public.channel (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_features ADD CONSTRAINT "FK_message_features_feature"
	FOREIGN KEY (feature) REFERENCES public.feature (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_features ADD CONSTRAINT "FK_message_features_message"
	FOREIGN KEY (message) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_functions ADD CONSTRAINT "FK_message_functions_function"
	FOREIGN KEY (function) REFERENCES public.function (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_functions ADD CONSTRAINT "FK_message_functions_message"
	FOREIGN KEY (message) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_nesting ADD CONSTRAINT "FK_message_nesting_message"
	FOREIGN KEY (ancestor) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_nesting ADD CONSTRAINT "FK_message_nesting_message_02"
	FOREIGN KEY (message) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_services ADD CONSTRAINT "FK_message_services_message"
	FOREIGN KEY (message) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_services ADD CONSTRAINT "FK_message_services_service"
	FOREIGN KEY (service) REFERENCES public.service (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_subject ADD CONSTRAINT "FK_message_subject_account_agent"
	FOREIGN KEY (account_agent) REFERENCES public.account_agent (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_subject ADD CONSTRAINT "FK_message_subject_message"
	FOREIGN KEY (message) REFERENCES public.message (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_subject ADD CONSTRAINT "FK_message_subject_subject_vector"
	FOREIGN KEY (subject_vector) REFERENCES public.subject_vector (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_subject_tag ADD CONSTRAINT "FK_message_subject_tag_message_subject"
	FOREIGN KEY (messsage_subject) REFERENCES public.message_subject (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.message_subject_tag ADD CONSTRAINT "FK_message_subject_tag_tag_vector"
	FOREIGN KEY (tag_vector) REFERENCES public.tag_vector (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.user_credential ADD CONSTRAINT "FK_user_credential_user"
	FOREIGN KEY ("user") REFERENCES public."user" (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.user_credential_oauth ADD CONSTRAINT "FK_user_credential_oauth_user_credential"
	FOREIGN KEY (identifier) REFERENCES public.user_credential (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.user_credential_login_pass ADD CONSTRAINT "FK_user_credential_login_pass_user_credential"
	FOREIGN KEY (identifier) REFERENCES public.user_credential (identifier) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE public.versioned_string_history ADD CONSTRAINT "FK_versioned_string_history_versioned_string"
	FOREIGN KEY (versioned_string) REFERENCES public.versioned_string (identifier) ON DELETE No Action ON UPDATE No Action
;
